### ISSUE TITLE
autoSaver 2.5 failure to run on QGIS 3.16.14

### ISSUE THREAD

**Issue by davidafuller01** [enricofer/autoSaver#16]
I just updated the plugin to 2.5 and it's no longer functioning. macOS Monterey 12.0.1.

```
An error has occurred while executing Python code: 

UnboundLocalError: local variable 'targetBakFile' referenced before assignment 
Traceback (most recent call last):
  File "/Users/userName/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/autoSaver/autosave.py", line 370, in cronEvent
    self.saveCurrentProject()
  File "/Users/userName/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/autoSaver/autosave.py", line 417, in saveCurrentProject
    self.iface.messageBar().pushSuccess("Autosaver", u"project autosaved to: "+targetBakFile)
UnboundLocalError: local variable 'targetBakFile' referenced before assignment


Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.16.14-Hannover Hannover, 4279198632 

Python Path:
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/userName/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/userName/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8
/Users/userName/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/userName/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res
/Users/userName/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs
/Users/userName/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
```

**Comment by enricofer** [comment]
Did you try to restart QGIS? Maybe clock schedule is not removed when upgrading plugin with autosave on

**Comment by davidafuller01** [comment]
Yes, I have restarted QGIS and rebooted my laptop (now on macOS Monterey 12.1). BTW...I do **NOT** have the alternate backup file option ticked on.

<img width="476" alt="Screen Shot 2021-12-15 at 1 27 28 PM" src="https://user-images.githubusercontent.com/2762809/146260308-56c492e8-5d73-4605-b7fd-b2cf172f44e3.png">

**Comment by enricofer** [comment]
fixed https://github.com/enricofer/autoSaver/commit/595b67c61b9de013dd843334cbb6963bd0f8b047
thanks for submission.
