### ISSUE TITLE
error on projects with unicode chars

### ISSUE THREAD

**Issue by enricofer** [enricofer/autoSaver#2]
from kalle@kronholm.cc

Very useful plugin! However, when using "strange" scandinavian letters like æ, ø, å in the file names, Python throws an error.

Error:
An error has occured while executing Python code:

Traceback (most recent call last):
File "C:/Users/Kalle/.qgis2/python/plugins\autoSaver\autosave.py", line 299, in cronEvent
self.saveCurrentProject()
File "C:/Users/Kalle/.qgis2/python/plugins\autoSaver\autosave.py", line 319, in saveCurrentProject
print "project autosaved to: ",bakFileName
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 52: ordinal not in range(128)

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.2-Wien Wien, 1b929ef

**Comment by enricofer** [comment]
thanks for submission.
