### ISSUE TITLE
Error on execution with v2.7

### ISSUE THREAD

**Issue by Skipper-is** [enricofer/autoSaver#23]
Version 2.7 throws an error on autosave:
`2023-05-22T08:21:42     WARNING    Traceback (most recent call last):
              File "**/python/plugins\autoSaver\autosave.py", line 364, in cronEvent
              self.saveCurrentProject()
              File "**python/plugins\autoSaver\autosave.py", line 412, in saveCurrentProject
              del os.environ['QGIS_PLUGIN_AUTO_SAVING']
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\os.py", line 695, in __delitem__
              raise KeyError(key) from None
             KeyError: 'QGIS_PLUGIN_AUTO_SAVING'
             `

Issue present on two versions of QGIS, 3.28.4 LTR  and 3.30.2.

**Comment by mrd83** [comment]
Resolved in [this PR](https://github.com/enricofer/autoSaver/pull/22). Hopefully it'll be merged soon...
