### ISSUE TITLE
Couldn't load plugin autoSaver due to an error when calling its initGui() method 

### ISSUE THREAD

**Issue by amsantac** [enricofer/autoSaver#3]
Hi. I tried to install the autoSaver plugin in QGIS 2.14.1 on Windows 8.1 and I got the following error:

Couldn't load plugin autoSaver due to an error when calling its initGui() method 

AttributeError: 'QCheckBox' object has no attribute 'setUnchecked' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 315, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/Guest/.qgis2/python/plugins\autoSaver\autosave.py", line 188, in initGui
    self.initAutoSaver()
  File "C:/Users/Guest/.qgis2/python/plugins\autoSaver\autosave.py", line 209, in initAutoSaver
    self.dlg.enableSaveLayersBuffer.setUnchecked(True)
AttributeError: 'QCheckBox' object has no attribute 'setUnchecked'

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.1-Essen Essen, ea85bef 

Python Path:
C:/Users/Guest/.qgis2/python/plugins\pktools
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/Guest/.qgis2/python
C:/Users/Guest/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Guest/.qgis2//python
C:\Users\Guest\.qgis2\python\plugins\gearthview\ext-libs
C:\Users\Guest\.qgis2\python\plugins
C:\Users\Guest\.qgis2\python\plugins\QuickMultiAttributeEdit/forms
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:/Users/Public/Documents/amsantac/qgs

**Comment by amsantac** [comment]
In spite of error mentioned aboved, it seems the plugin has been installed and it works. Thanks.
