### ISSUE TITLE
Rilevato errore

### ISSUE THREAD

**Issue by Korto19** [enricofer/autoSaver#7]
Si è verificato un errore durante l'esecuzione del codice Python: 

AttributeError: type object 'QgsMessageBar' has no attribute 'SUCCESS' 
Traceback (most recent call last):
  File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\autoSaver\autosave.py", line 366, in cronEvent
    self.saveCurrentProject()
  File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\autoSaver\autosave.py", line 396, in saveCurrentProject
    self.iface.messageBar().pushMessage("Autosave", u"project autosaved to: "+bakFileName, level=qgis.gui.QgsMessageBar.SUCCESS, duration=10 )
AttributeError: type object 'QgsMessageBar' has no attribute 'SUCCESS'

Versione Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Versione di QGIS: 3.0.0-Girona Girona, 001c80b0c3 

Percorso Python:
C:/OSGEO4~2/apps/qgis/./python
C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~2/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~2\apps\Python36\DLLs
C:\OSGEO4~2\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~2\apps\Python36
C:\OSGEO4~2\apps\Python36\lib\site-packages
C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by enricofer** [comment]
E' la stessa api break rilevata qui: https://github.com/enricofer/go2streetview/issues/35
Grazie per la segnalazione
